service: concat-videos-icods
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::*"

functions:
  hello:
    handler: handler.handle
    events:
      - s3:
          bucket: studio-icods
          event: s3:ObjectCreated:*
          rules:
            - suffix: .mp4