service: concat-videos
frameworkVersion: "2"
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 120
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${env:ICODS_VIDEO_BUCKET}/*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${env:ICODS_VIDEO_OUTPUT_BUCKET}/*"

functions:
  concat:
    handler: src/handler.concat
    events:
      - s3: ${env:ICODS_VIDEO_BUCKET}
    layers:
      - { Ref: FfmpegLambdaLayer }

plugins:
  - serverless-dotenv-plugin

layers:
  ffmpeg:
    path: layer

resources:
  Resources:
    OutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:ICODS_VIDEO_OUTPUT_BUCKET}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
