service: concat-videos
frameworkVersion: "2"
useDotenv: true
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:deleteObject
      Resource: "arn:aws:s3:::${env:ICODS_VIDEO_BUCKET}/*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${env:ICODS_VIDEO_OUTPUT_BUCKET}/*"

functions:
  concat:
    timeout: 200
    memorySize: 768
    handler: src/handler.concat
    events:
      - s3: ${env:ICODS_VIDEO_BUCKET}
    layers:
      - { Ref: FfmpegLambdaLayer }

plugins:
  - serverless-dotenv-plugin

layers:
  ffmpeg:
    path: layer
