
service: join-videos

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: us-east-1
  memorySize: 512
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  video_handler:
    handler: video_handler.handle
    environment:
      bucket: bucket-icods-videos
    events:
      - s3:
          bucket: bucket-icods-videos
          event: s3:ObjectCreated:*

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux